name: Vantage6 Algorithm CI

on:
  push:
    branches:
      - main
    tags:
      - 'release/v*.*.*'
      - 'dev'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

  build-and-push:
    name: Build and Push Docker Image
    if: startsWith(github.ref, 'refs/tags/release/v') || github.ref == 'refs/tags/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Downcase REPO name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (release)
        if: startsWith(github.ref, 'refs/tags/release/v')
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:latest
            ghcr.io/${{ env.REPO }}:${{ steps.extract_tag.outputs.tag }}

      - name: Build and push Docker image (dev)
        if: github.ref == 'refs/tags/dev'
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ env.REPO }}:dev
